version: '3.3'

services:
  db:
    image: mysql:latest
    container_name: task1_mysql_container
    restart: always
    command: --sql_mode=""
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DB_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '${DB_PORT}:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db: